version: "3.12"

services:
    db:
      image: postgres:15
      container_name: my_postgres_for_app
      command: -p 5432
      expose:
        - 5432
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASS}
        - POSTGRES_DB=${DB_NAME}
      volumes:
        - postgres:/var/lib/postgres/data
      networks:
        - network



    app:
        container_name: my_project_app
        build: .
        command: uvicorn src.main:app --host 0.0.0.0 --port 80
        env_file:
          - .env
        ports:
          - 80:80
        depends_on:
          - db
        networks:
          - network


networks:
  network:
    driver: bridge

volumes:
  postgres:
  uploads:

